"use client";

import { useState, useRef, useCallback, useEffect, useMemo } from "react";
import Image from "next/image";
import type { GenerationResult } from "@/types/generations";
import { IconRegenerate, IconUpscale, IconCopy, IconDownload, IconEdit } from "./Icons";

// --- Gallery Card ---

export function GalleryCard({
  result,
  isFeatured,
  onDownload,
  onCopyUrl,
  onEdit,
  onRegenerate,
  onFavorite,
  onDelete,
  onClick,
  copied,
  onImageLoad,
  isLoaded,
  onMediaLoaded,
  selectMode,
  selected,
  onToggleSelect,
}: {
  result: GenerationResult;
  isFeatured: boolean;
  onDownload: () => void;
  onCopyUrl: () => void;
  onEdit: () => void;
  onRegenerate: () => void;
  onFavorite: () => void;
  onDelete: () => void;
  onClick: () => void;
  copied: boolean;
  onImageLoad?: (url: string, w: number, h: number) => void;
  isLoaded?: boolean;
  onMediaLoaded?: (url: string) => void;
  selectMode?: boolean;
  selected?: boolean;
  onToggleSelect?: () => void;
}) {
  const [hovered, setHovered] = useState(false);
  const [localLoaded, setLocalLoaded] = useState(false);
  const loaded = (isLoaded ?? false) || localLoaded;

  const handleMediaReady = useCallback(() => {
    setLocalLoaded(true);
    onMediaLoaded?.(result.imageUrl);
  }, [onMediaLoaded, result.imageUrl]);

  const handleClick = selectMode ? (onToggleSelect ?? onClick) : onClick;

  return (
    <div
      className={`group relative h-full w-full cursor-pointer overflow-hidden rounded-lg transition-all ${
        selectMode && selected ? "ring-2 ring-accent ring-offset-1 ring-offset-background" : ""
      }`}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      onClick={handleClick}
      draggable={!selectMode}
      onDragStart={(e) => {
        if (selectMode) { e.preventDefault(); return; }
        e.dataTransfer.setData("text/uri-list", result.imageUrl);
        e.dataTransfer.setData("text/plain", result.imageUrl);
        e.dataTransfer.effectAllowed = "copy";
      }}
    >
      {/* Select mode checkbox */}
      {selectMode && (
        <div className="absolute left-2 top-2 z-20">
          <span
            className={`flex h-5 w-5 items-center justify-center rounded-md border-[1.5px] transition ${
              selected ? "border-accent bg-accent" : "border-white/60 bg-black/40 backdrop-blur-sm"
            }`}
          >
            {selected && (
              <svg width="11" height="11" viewBox="0 0 10 10" fill="none" stroke="black" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="M2 5l2.5 2.5L8 3" />
              </svg>
            )}
          </span>
        </div>
      )}

      {/* Pending generation — show generating indicator */}
      {result.pending && (
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 rounded-lg bg-surface">
          <div className="h-5 w-5 animate-spin rounded-full border-2 border-accent border-t-transparent" />
          <span className="text-[10px] font-medium text-muted">Generating...</span>
          <span className="text-[8px] text-muted/60">{result.model}</span>
        </div>
      )}
      {/* Skeleton placeholder until media loads */}
      {!result.pending && !loaded && (
        <div className="absolute inset-0 animate-pulse rounded-lg bg-surface" />
      )}
      {!result.pending && (result.type === "video" ? (
        <>
          <video
            src={result.imageUrl}
            className={`h-full w-full rounded-lg object-cover transition-opacity duration-300 ${loaded ? "opacity-100" : "opacity-0"}`}
            muted
            loop
            playsInline
            preload="metadata"
            draggable={false}
            onLoadedData={handleMediaReady}
            onLoadedMetadata={handleMediaReady}
            onMouseEnter={(e) => (e.target as HTMLVideoElement).play().catch(() => {})}
            onMouseLeave={(e) => { const v = e.target as HTMLVideoElement; v.pause(); v.currentTime = 0; }}
          />
          {/* Play icon overlay */}
          {loaded && (
            <div className="pointer-events-none absolute inset-0 flex items-center justify-center transition-opacity group-hover:opacity-0">
              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-black/50 backdrop-blur-sm">
                <svg width="14" height="14" viewBox="0 0 14 14" fill="white" stroke="none">
                  <path d="M4 2.5l8 4.5-8 4.5V2.5z" />
                </svg>
              </div>
            </div>
          )}
        </>
      ) : (
        <Image
          src={result.imageUrl || "/placeholder.svg"}
          alt={`Generated by ${result.model}`}
          fill
          sizes="(max-width: 768px) 50vw, 33vw"
          quality={75}
          className={`rounded-lg object-cover transition-opacity duration-300 ${loaded ? "opacity-100" : "opacity-0"}`}
          draggable={false}
          onLoad={(e) => {
            handleMediaReady();
            const img = e.target as HTMLImageElement;
            onImageLoad?.(result.imageUrl, img.naturalWidth, img.naturalHeight);
          }}
        />
      ))}

      {/* Model badge */}
      {!selectMode && (
        <div className="absolute left-1.5 top-1.5 rounded-md bg-black/40 px-1.5 py-px text-[8px] font-medium text-white/60 backdrop-blur-sm transition-opacity group-hover:opacity-100 opacity-0">
          {result.model.replace(/\s*\(Edit\)/i, "")}
        </div>
      )}

      {/* Favorite heart */}
      {!selectMode && (
        <button
          onClick={(e) => { e.stopPropagation(); onFavorite(); }}
          className={`absolute right-2 top-2 flex h-6 w-6 items-center justify-center rounded-full transition ${
            result.favorited
              ? "bg-black/50 text-red-400 opacity-100"
              : `bg-black/40 text-white/60 hover:text-red-400 ${hovered ? "opacity-100" : "opacity-0"}`
          }`}
        >
          <svg width="12" height="12" viewBox="0 0 14 14" fill={result.favorited ? "currentColor" : "none"} stroke="currentColor" strokeWidth="1.5">
            <path d="M7 12.5S1 8.5 1 5a3 3 0 015.5-1.5h1A3 3 0 0113 5c0 3.5-6 7.5-6 7.5z" />
          </svg>
        </button>
      )}

      {/* Hover overlay — actions (hidden in select mode) */}
      {!selectMode && <div
        className={`absolute inset-x-0 bottom-0 flex items-center justify-end gap-0.5 rounded-b-lg bg-gradient-to-t from-black/60 to-transparent px-2 pb-2 pt-6 transition-opacity duration-200 ${
          hovered ? "opacity-100" : "opacity-0"
        }`}
        onClick={(e) => e.stopPropagation()}
      >
        <button onClick={onDownload} className="rounded-md p-1.5 text-white/70 transition hover:bg-white/10 hover:text-white" title="Download">
          <IconDownload />
        </button>
        <button onClick={() => {/* TODO */}} className="rounded-md p-1.5 text-white/70 transition hover:bg-white/10 hover:text-white" title="Upscale">
          <IconUpscale />
        </button>
        <button onClick={onCopyUrl} className="rounded-md p-1.5 text-white/70 transition hover:bg-white/10 hover:text-white" title="Copy URL">
          {copied ? (
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
              <path d="M2 7l4 4L12 3" className="text-accent" />
            </svg>
          ) : (
            <IconCopy />
          )}
        </button>
        <button onClick={(e) => { e.stopPropagation(); onDelete(); }} className="rounded-md p-1.5 text-white/70 transition hover:bg-white/10 hover:text-red-400" title="Delete">
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
            <path d="M2 4h10M5 4V2.5h4V4M3 4l.7 8.1c.1.8.7 1.4 1.5 1.4h3.6c.8 0 1.4-.6 1.5-1.4L11 4" />
          </svg>
        </button>
      </div>}
    </div>
  );
}

// --- Justified Row Layout ---

interface GalleryItem {
  type: "result";
  result: GenerationResult;
  aspectRatio: number;
}

interface GallerySlot {
  type: "slot";
  slotId: string;
  modelId: string;
  modelName: string;
  aspectRatio: number;
}

export type GalleryEntry = GalleryItem | GallerySlot;

const ROW_HEIGHT_LANDSCAPE = 160;
const ROW_HEIGHT_SQUARE = 210;
const ROW_HEIGHT_PORTRAIT = 300;

function getDominantHeight(row: GalleryEntry[], scale: number): number {
  let portrait = 0;
  let landscape = 0;
  let square = 0;
  for (const e of row) {
    const ar = e.aspectRatio;
    if (ar < 0.85) portrait++;
    else if (ar > 1.2) landscape++;
    else square++;
  }
  let base: number;
  if (portrait >= landscape && portrait >= square) base = ROW_HEIGHT_PORTRAIT;
  else if (landscape >= portrait && landscape >= square) base = ROW_HEIGHT_LANDSCAPE;
  else base = ROW_HEIGHT_SQUARE;
  return base * scale;
}

export function buildJustifiedRows(
  items: GalleryEntry[],
  containerWidth: number,
  scale: number,
  gap: number
): GalleryEntry[][] {
  if (containerWidth <= 0 || items.length === 0) return [];

  const rows: GalleryEntry[][] = [];
  let currentRow: GalleryEntry[] = [];

  for (const item of items) {
    currentRow.push(item);

    const totalGap = (currentRow.length - 1) * gap;
    const availableWidth = containerWidth - totalGap;
    const totalAR = currentRow.reduce((sum, e) => sum + e.aspectRatio, 0);
    const rowHeight = availableWidth / totalAR;

    const targetHeight = getDominantHeight(currentRow, scale);

    if (rowHeight <= targetHeight) {
      rows.push(currentRow);
      currentRow = [];
    }
  }

  if (currentRow.length > 0) {
    rows.push(currentRow);
  }

  return rows;
}

// --- Gallery Grid ---

export interface GalleryGridProps {
  results: GenerationResult[];
  latestBatchId: string | null;
  generatingSlots: { modelName: string; modelId: string; slotId: string }[];
  isGenerating: boolean;
  showEditPrompt: boolean;
  editPromptValue: string;
  setEditPromptValue: (v: string) => void;
  error: string | null;
  copiedId: string | null;
  targetRowHeight: number;
  slotAspectRatio: number;
  onRegenerate: () => void;
  onEdit: () => void;
  onEditSubmit: () => void;
  setShowEditPrompt: (v: boolean) => void;
  onDownload: (r: GenerationResult) => void;
  onCopyUrl: (r: GenerationResult) => void;
  onClickImage: (r: GenerationResult) => void;
  onFavorite: (requestId: string) => void;
  onDelete: (requestId: string) => void;
  // Select mode
  selectMode?: boolean;
  selectedIds?: Set<string>;
  onToggleSelect?: (requestId: string) => void;
}

export function GalleryGrid({
  results,
  latestBatchId,
  generatingSlots,
  isGenerating,
  showEditPrompt,
  editPromptValue,
  setEditPromptValue,
  error,
  copiedId,
  targetRowHeight,
  slotAspectRatio,
  onRegenerate,
  onEdit,
  onEditSubmit,
  setShowEditPrompt,
  onDownload,
  onCopyUrl,
  onClickImage,
  onFavorite,
  onDelete,
  selectMode,
  selectedIds,
  onToggleSelect,
}: GalleryGridProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [containerWidth, setContainerWidth] = useState(0);
  const [arCache, setArCache] = useState<Record<string, number>>({});
  const arCacheRef = useRef(arCache);
  arCacheRef.current = arCache;
  const [loadedUrls, setLoadedUrls] = useState<Set<string>>(() => new Set());
  const markLoaded = useCallback((url: string) => {
    setLoadedUrls((prev) => { if (prev.has(url)) return prev; const next = new Set(prev); next.add(url); return next; });
  }, []);

  const onImageLoad = useCallback((url: string, naturalW: number, naturalH: number) => {
    if (naturalW > 0 && naturalH > 0 && !arCacheRef.current[url]) {
      setArCache((prev) => ({ ...prev, [url]: naturalW / naturalH }));
    }
  }, []);

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const obs = new ResizeObserver((entries) => {
      const w = entries[0]?.contentRect.width ?? 0;
      if (w > 0) setContainerWidth(w);
    });
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  const latestIds = new Set(
    latestBatchId ? results.filter((r) => r.batchId === latestBatchId).map((r) => r.requestId) : []
  );
  const hasLatestBatch = latestIds.size > 0;
  const gap = 6;

  const entries: GalleryEntry[] = [
    ...generatingSlots.map((slot): GallerySlot => ({
      type: "slot",
      slotId: slot.slotId,
      modelId: slot.modelId,
      modelName: slot.modelName,
      aspectRatio: slotAspectRatio,
    })),
    ...results.map((r): GalleryItem => {
      let ar = arCache[r.imageUrl];
      if (!ar && r.width && r.height) {
        ar = r.width / r.height;
      }
      if (!ar && r.settings?.aspectRatio) {
        const [w, h] = r.settings.aspectRatio.split(":").map(Number);
        if (w && h) ar = w / h;
      }
      if (!ar) ar = r.type === "video" ? 16 / 9 : 1;
      return { type: "result", result: r, aspectRatio: ar };
    }),
  ];

  const allRows = buildJustifiedRows(entries, containerWidth, targetRowHeight, gap);

  // Progressive rendering — mount first INITIAL_ROWS immediately,
  // reveal more as user scrolls. Keeps DOM light and prevents
  // hundreds of image/video requests from saturating the browser.
  const INITIAL_ROWS = 8;
  const ROWS_PER_BATCH = 6;
  const [visibleRowCount, setVisibleRowCount] = useState(INITIAL_ROWS);
  const sentinelRef = useRef<HTMLDivElement>(null);

  // Reset visible count when total rows change (e.g., filter change)
  useEffect(() => {
    setVisibleRowCount(INITIAL_ROWS);
  }, [allRows.length]);

  // IntersectionObserver to load more rows on scroll
  useEffect(() => {
    const sentinel = sentinelRef.current;
    if (!sentinel) return;
    if (visibleRowCount >= allRows.length) return;
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setVisibleRowCount((prev) => Math.min(prev + ROWS_PER_BATCH, allRows.length));
        }
      },
      { rootMargin: "400px" }
    );
    obs.observe(sentinel);
    return () => obs.disconnect();
  }, [visibleRowCount, allRows.length]);

  const rows = allRows.slice(0, visibleRowCount);

  return (
    <div ref={containerRef} className="overflow-hidden">
      {/* Status bar */}
      {(isGenerating || error || (!isGenerating && hasLatestBatch)) && (
        <div className="mb-2.5 flex items-center justify-between">
          {isGenerating ? (
            <div className="flex items-center gap-2">
              <div className="h-1.5 w-1.5 animate-pulse rounded-full bg-accent" />
              <span className="text-[10px] font-medium uppercase tracking-wider text-muted/60">
                Generating {generatingSlots.length} {generatingSlots.length === 1 ? "item" : "items"}
              </span>
            </div>
          ) : (
            <div />
          )}
          {!isGenerating && hasLatestBatch && (
            <button
              onClick={onRegenerate}
              className="flex items-center gap-1.5 text-[10px] font-medium text-accent/70 transition hover:text-accent"
            >
              <IconRegenerate /> Regenerate
            </button>
          )}
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="mb-2.5 rounded-lg border border-destructive/20 bg-destructive/5 px-3 py-2 text-[11px] text-destructive/80">
          {error}
        </div>
      )}

      {/* Edit prompt inline */}
      {showEditPrompt && hasLatestBatch && (
        <div className="mb-2.5 flex items-center gap-2 rounded-xl border border-border bg-surface px-3 py-2">
          <IconEdit />
          <input
            type="text"
            value={editPromptValue}
            onChange={(e) => setEditPromptValue(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") onEditSubmit();
              if (e.key === "Escape") setShowEditPrompt(false);
            }}
            placeholder="Describe the edit..."
            className="flex-1 bg-transparent text-sm text-foreground outline-none placeholder:text-muted"
            autoFocus
          />
          <button
            onClick={onEditSubmit}
            disabled={!editPromptValue.trim()}
            className="shrink-0 rounded-md bg-accent px-3 py-1 text-[10px] font-semibold text-black transition hover:bg-accent-hover disabled:opacity-30"
          >
            Go
          </button>
          <button
            onClick={() => setShowEditPrompt(false)}
            className="text-[10px] text-muted transition hover:text-foreground"
          >
            Cancel
          </button>
        </div>
      )}

      {/* Justified row gallery */}
      {containerWidth > 0 && (
        <div className="flex flex-col" style={{ gap }}>
          {rows.map((row, rowIdx) => {
            const totalGap = (row.length - 1) * gap;
            const availableWidth = containerWidth - totalGap;
            const totalAR = row.reduce((sum, e) => sum + e.aspectRatio, 0);
            const justifiedHeight = availableWidth / totalAR;
            const dominantHeight = getDominantHeight(row, targetRowHeight);
            const isLastRow = rowIdx === rows.length - 1;
            const rowHeight = (isLastRow && row.length <= 2 && justifiedHeight > dominantHeight * 1.5)
              ? dominantHeight
              : justifiedHeight;

            return (
              <div key={rowIdx} className="flex" style={{ gap, height: rowHeight }}>
                {row.map((entry) => {
                  if (entry.type === "slot") {
                    return (
                      <div
                        key={entry.slotId}
                        className="relative min-w-0 overflow-hidden rounded-lg"
                        style={{ flex: `1 1 ${rowHeight * entry.aspectRatio}px`, height: rowHeight }}
                      >
                        <div className="absolute inset-0 animate-pulse bg-surface" />
                        <div className="absolute inset-0 -translate-x-full animate-[shimmer_1.8s_ease-in-out_infinite] bg-gradient-to-r from-transparent via-accent/[0.07] to-transparent" />
                        <div className="absolute inset-0 flex flex-col items-center justify-center gap-2">
                          <div className="h-6 w-24 animate-pulse rounded-md bg-border/40" />
                          <span className="animate-pulse text-[10px] font-medium text-muted/50">
                            {entry.modelName}
                          </span>
                        </div>
                      </div>
                    );
                  }

                  const r = entry.result;
                  const isLatest = latestIds.has(r.requestId);

                  return (
                    <div
                      key={r.requestId}
                      className="min-w-0"
                      style={{ flex: `1 1 ${rowHeight * entry.aspectRatio}px`, height: rowHeight }}
                    >
                      <GalleryCard
                        result={r}
                        isFeatured={isLatest}
                        onDownload={() => onDownload(r)}
                        onCopyUrl={() => onCopyUrl(r)}
                        onEdit={onEdit}
                        onRegenerate={onRegenerate}
                        onFavorite={() => onFavorite(r.requestId)}
                        onDelete={() => onDelete(r.requestId)}
                        onClick={() => onClickImage(r)}
                        copied={copiedId === r.requestId}
                        onImageLoad={onImageLoad}
                        isLoaded={loadedUrls.has(r.imageUrl)}
                        onMediaLoaded={markLoaded}
                        selectMode={selectMode}
                        selected={selectedIds?.has(r.requestId)}
                        onToggleSelect={() => onToggleSelect?.(r.requestId)}
                      />
                    </div>
                  );
                })}
              </div>
            );
          })}
        </div>
      )}
      {/* Sentinel for infinite scroll — triggers loading more rows */}
      {visibleRowCount < allRows.length && (
        <div ref={sentinelRef} className="h-px" />
      )}
    </div>
  );
}
